### ISSUE TITLE
webui打不开

### ISSUE THREAD

**Issue by dengqj** [zu1k/zlib-searcher#1]

**Comment by zu1k** [comment]
信息不足

**Comment by dengqj** [comment]
![屏幕截图 2022-11-25 193158](https://user-images.githubusercontent.com/10740870/203976734-62e17076-d132-4774-acb0-403d02bd87a6.jpg)
打开http://[127.0.0.1:7070](http://127.0.0.1:7070/)/的界面是空白的

**Comment by zu1k** [comment]
看看网络请求js/css什么的加载是不是有问题

**Comment by zu1k** [comment]
你下载的是哪个版本？下载最新的 0.4.2 试试，index 也需要重新下载

**Comment by dengqj** [comment]
最新版成功了！感谢！
