### ISSUE TITLE
[question] why frontend and backend are in different branch?

### ISSUE THREAD

**Issue by yihong0618** [zu1k/zlib-searcher#12]
A bit of trouble to build

**Comment by zu1k** [comment]
This is because this backend does not have to be bound to the front end, and other native programs can also be developed.

Or we can also develop a client using tauri.

The most important point is that I am not familiar with front-end development. You can find two front-end branches. I have done some experiments.

**Comment by yihong0618** [comment]
> This is because this backend does not have to be bound to the front end, and other native programs can also be developed.
> 
> Or we can also develop a client using tauri.
> 
> The most important point is that I am not familiar with front-end development. You can find two front-end branches. I have done some experiments.

yes...but for now, the backend build needs frontend so kind of trouble IMO

**Comment by zu1k** [comment]
maybe we can change the dist path to be embeded, and make a soft link before cargo run

**Comment by zu1k** [comment]
I can change this line from `../zlib-searcher-frontend/dist` to `./frontend/dist`.

https://github.com/zu1k/zlib-searcher/blob/aea0ce8682fefedcfd6d532229794159402d9c28/build.rs#L4

First `mkdir frontend && git --work-tree=./frontend checkout frontend -- .`, this will checkout `frontend` branch to `./frontend dir`.

Then `pushd ./frontend && pnpm install && pnpm run build`, this will build dist in `frontend/dist`.

Last `popd && cargo build --release`.

**Comment by zu1k** [comment]
After careful consideration, for the benign development of the project, I think I should merge the front end into the main branch.

**Comment by zu1k** [comment]
> I think I should merge the front end into the main branch

DONE
