### ISSUE TITLE
how to make use of local ipfs

### ISSUE THREAD

**Issue by Yaoxiao1** [zu1k/zlib-searcher#16]
per your comment in https://github.com/zu1k/zlib-searcher/pull/15
I'd like to learn how to make use of that port, but when i press that button, it returns Jenkins login page?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/34466246/204567025-2a12b031-d752-40a7-902c-ff88fdaf724c.png">
I guess 8080 is the port for ipfs, but not everyone knows that.
I think it is better to name out what that tag means, or people may get confused
Thank you

**Comment by zu1k** [comment]
This is because the port conflict , and is indeed not clear enough here, and it will be improved later.

**Comment by Yaoxiao1** [comment]
yes I have read your blog about IPFS, 
wish you could make that decentralized file system happen.
