### ISSUE TITLE
cannot open webui with docker deployed

### ISSUE THREAD

**Issue by chinobing** [zu1k/zlib-searcher#22]
![image](https://user-images.githubusercontent.com/27722028/204734170-2e1eec4a-316c-43d3-9703-11ba2990be76.png)

**Comment by zu1k** [comment]
I have no problem testing on my local, I need more information

**Comment by zu1k** [comment]
This instance is using the docker image version 0.6.0, https://zlib.knat.network/ , everything looks ok.

**Comment by chinobing** [comment]
okok, i am not really sure why is that.. I am checking my setup now
