### ISSUE TITLE
[feat] Develop a desktop app with tauri

### ISSUE THREAD

**Issue by zu1k** [zu1k/zlib-searcher#24]
I'm not familiar with the front-end, currently made a small demo, look forward to improving together.

https://github.com/zu1k/zlib-searcher/tree/desktop

**Comment by Wybxc** [comment]
I'm currently working on a demo when I heard of this. I'm glad we have the same idea.

There is more can be done making use of a desktop app, such as automaticly download index files and books via IPFS RPC.

**Comment by zu1k** [comment]
We need a rust version downloader to do IPFS rpc or download file from other public gateways, and we need to launch an IPFS daemon instance on the background.

**Comment by zu1k** [comment]
We also need to use the same frontend code, and decide to compile the desktop version that uses js-bridge or the web version through a certain compilation parameter.

**Comment by Wybxc** [comment]
> We need a rust version downloader to do IPFS rpc or download file from other public gateways, and we need to launch an IPFS daemon instance on the background.

We don't need to manage IPFS daemon. Just indicate the users to start IPFS daemon or IPFS Desktop by themselves.

**Comment by zu1k** [comment]
> Just indicate the users to start IPFS daemon or IPFS Desktop by themselves.

That's also ok.

Do you have a demo? My frontend code was lost,lol

**Comment by Wybxc** [comment]
I will make my PR when I finish it.

**Comment by zu1k** [comment]
We created 4 basic bundles for everyone to test.

https://github.com/zu1k/zlib-searcher/actions/runs/3618254150

- MacOS: dmg
- Windows: msi
- Linux(based on ubuntu 20.04): deb / appimage
