### ISSUE TITLE
You should have your own index locally !

### ISSUE THREAD

**Issue by zu1k** [zu1k/zlib-searcher#3]
I posted a demo at https://zlib.zu1k.com/, so everyone is using this as a production environment.
It's hard to imagine how poor my 1 core 1G server is to withstand such a large amount of queries.

This is not what I expect, I hope everyone who wants to use it will follow the steps in the readme to build their own search service in their own local area. This not only provides a faster search experience, but also avoids certain possible legal risks.

https://zlib.zu1k.com does not guarantee quality of service and may stop service at some point in the future, but your local search service will not.

**Comment by zu1k** [comment]
![image](https://user-images.githubusercontent.com/42370281/204468378-b5df21bd-9db9-4f40-98c1-c31a654217d0.png)

**Comment by n0vad3v** [comment]
Nice work, now I'm hosting a mirror at https://zlib.knat.network/ , maybe this can do some help!

**Comment by chris-ss** [comment]
hosting a mirror at https://zlib.awesc.com/

**Comment by Seas0** [comment]
IMAO it maybe helpful to also pin the index file on IPFS. So why not provide a IPFS hash for the index?

**Comment by zu1k** [comment]
> So why not provide a IPFS hash for the index?

There may be a certain risk of leaking my ip

**Comment by GaryLz** [comment]
Thanks for the kind favor for us.
