### ISSUE TITLE
I could use your service as a API?

### ISSUE THREAD

**Issue by trasherwngs** [zu1k/zlib-searcher#36]
Hello developers, I am currently creating a bot for the Discord platform, where one of its features, is to search for specific books in Z-Library and I would like to use your service as a form of API request, how can I do it?

I took a look at the "Network" tab in my browser's developer options, and saw that I had an API linked to the site below:

https://zlib.knat.network/search?limit=100&query=THEBOOKHERE

In my Windows browser the request works normally, but when I try to pass it to the bot it inserts several characters as a form of encryption. Could you please give me a solution?

https://prnt.sc/V2RwCe6x22JE

**Comment by zu1k** [comment]
I need more information

**Comment by trasherwngs** [comment]
I would like to be able to use your API, however, I believe CloudFlare is protecting the domain from being able to use it. Do you know of anything that I can bypass or something of the sort that would make me allow access directly from my bot?

**Comment by zu1k** [comment]
Just deploy your own one.
