### ISSUE TITLE
调整建议：列宽、简繁体搜索

### ISSUE THREAD

**Issue by a2423249329** [zu1k/zlib-searcher#39]
1. 书名栏列宽过窄。如果书名过长，则无法完整显示其书名，影响判断。
2. 初版社栏列宽过长。出版社并非检索时必需的“重要信息”，建议把这一栏缩短，or直接删掉，or放在书名信息中做二级展开。
3. 同一本中文书，简繁体搜索结果不一样。建议搜索中文时合并简繁体信息。

**Comment by zu1k** [comment]
The third needs to be carefully considered, the rest have been resolved.

**Comment by a2423249329** [comment]
> The third needs to be carefully considered, the rest have been resolved.

thank you,wish we could have the better one as soon as possible with more convenience and utility.
