### ISSUE TITLE
老铁不能顺便打包个macos的吗？

### ISSUE THREAD

**Issue by youwillbe** [zu1k/zlib-searcher#7]
如题

**Comment by fierceX** [comment]
我有m1的，要的话给个邮箱

**Comment by zu1k** [comment]
后面会有 ci 编译全平台的二进制，可以等 #5

**Comment by youwillbe** [comment]
> 我有m1的，要的话给个邮箱

英特尔的，算了，等等吧

**Comment by youwillbe** [comment]
> 后面会有 ci 编译全平台的二进制，可以等 #5

那太好了

**Comment by meterscao** [comment]
[> ](https://github.com/zu1k/zlib-searcher/issues/7#issuecomment-1330374188)

蹲一个，感谢，meterscao at gmail

**Comment by materliu** [comment]
> 我有m1的，要的话给个邮箱

so thx。materliu at gmail

**Comment by fierceX** [comment]
@materliu https://1drv.ms/u/s!Ak_PhqGBAudojIlaNTuvSNichLNyOw?e=PaeMlR
